services:
  bot:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    configs:
      - source: up_config
        target: /app/config.toml
    secrets:
      - source: up_secrets
        target: /app/secrets.toml
    logging:
      driver: awslogs
      options:
        awslogs-group: underpeel-bot-logs
        awslogs-stream: underpeel-bot

configs:
  up_config:
    file: ./config.toml

secrets:
  up_secrets:
    file: ./secrets.toml
