services:
  bot:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - sqlite-data:/app/sqlite-data
    configs:
      - source: up_config
        target: /app/config.toml
    secrets:
      - source: up_secrets
        target: /app/secrets.toml
    logging:
      driver: awslogs
      options:
        awslogs-group: underpeel-bot-logs
        awslogs-stream: underpeel-bot

volumes:
  sqlite-data:

configs:
  up_config:
    file: ./config.toml

secrets:
  up_secrets:
    file: ./secrets.toml
