production_mode = false
dynamodb_table = "discord-members"

discord_server_id = 12345
board_role_id = 12345
mod_role_id = 12345
dev_role_id = 12345
logistics_role_id = 12345

non_robomoji_categories = [
  12345,
  67890,
]
non_robomoji_channels = [
  12345,
  67890,
]

up_participation_roles = [
  12345,
  67890,
]
